# module: textfile.py
# Handle text files generated by
# alesis micron/ion program decoder/encoder.

### Read sysex.txt into settings
def import_file(file_name):
    txt_file = open(file_name)
    settings = {'file_name':file_name}
    for line in txt_file:
        line = line.strip()
        if line:
            if not line.startswith('#'): # remove comments
                pair = line.split(':')
                name = pair[0].replace(' ','_')
                value = pair[1].strip()
                settings[name] = value
    txt_file.close()
    return settings

### Export settings into sysex.txt - TODO
